project:
  type: website
  output-dir: docs

website:
  title: "Data Science Blogs"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Farhan-Faisal

format:
  html:
    theme: flatly
    css: styles.css




